// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantMS.Infrastructure.Data;

#nullable disable

namespace RestaurantMS.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260409072851_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("RestaurantMS.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("RestaurantMS.Domain.Entities.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Areas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Tầng trệt (Trong nhà)"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Tầng 2 (VIP)"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sân thượng (View hồ)"
                        });
                });

            modelBuilder.Entity("RestaurantMS.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Khai vị",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Món chính",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Lẩu & Combo",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Tráng miệng",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Name = "Đồ uống",
                            SortOrder = 5
                        });
                });

            modelBuilder.Entity("RestaurantMS.Domain.Entities.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TagsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 4, 9, 7, 28, 51, 777, DateTimeKind.Utc).AddTicks(4611),
                            IsAvailable = true,
                            Name = "Salad Ức Gà",
                            Price = 65000m,
                            TagsJson = "[\"Healthy\"]"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 4, 9, 7, 28, 51, 777, DateTimeKind.Utc).AddTicks(4622),
                            IsAvailable = true,
                            Name = "Súp Bào Ngư",
                            Price = 120000m,
                            TagsJson = "[\"Special\"]"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 4, 9, 7, 28, 51, 777, DateTimeKind.Utc).AddTicks(4624),
                            IsAvailable = true,
                            Name = "Khoai Tây Chiên Bơ Tỏi",
                            Price = 45000m,
                            TagsJson = "[]"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 4, 9, 7, 28, 51, 777, DateTimeKind.Utc).AddTicks(4625),
                            IsAvailable = true,
                            Name = "Nộm Ngó Sen Tôm Thịt",
                            Price = 85000m,
                            TagsJson = "[]"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 4, 9, 7, 28, 51, 777, DateTimeKind.Utc).AddTicks(4627),
                            IsAvailable = true,
                            Name = "Bò Bít Tết Mỹ",
                            Price = 250000m,
                            TagsJson = "[\"Best Seller\"]"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 4, 9, 7, 28, 51, 777, DateTimeKind.Utc).AddTicks(4628),
                            IsAvailable = true,
                            Name = "Cá Hồi Áp Chảo",
                            Price = 185000m,
                            TagsJson = "[]"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 4, 9, 7, 28, 51, 777, DateTimeKind.Utc).AddTicks(4629),
                            IsAvailable = true,
                            Name = "Sườn Nướng BBQ",
                            Price = 210000m,
                            TagsJson = "[]"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 4, 9, 7, 28, 51, 777, DateTimeKind.Utc).AddTicks(4631),
                            IsAvailable = true,
                            Name = "Cơm Chiên Hải Sản",
                            Price = 95000m,
                            TagsJson = "[]"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 4, 9, 7, 28, 51, 777, DateTimeKind.Utc).AddTicks(4632),
                            IsAvailable = true,
                            Name = "Mỳ Ý Sốt Bò Bằm",
                            Price = 115000m,
                            TagsJson = "[]"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 4, 9, 7, 28, 51, 777, DateTimeKind.Utc).AddTicks(4633),
                            IsAvailable = true,
                            Name = "Lẩu Thái Hải Sản",
                            Price = 450000m,
                            TagsJson = "[]"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 4, 9, 7, 28, 51, 777, DateTimeKind.Utc).AddTicks(4634),
                            IsAvailable = true,
                            Name = "Combo Gia Đình (4 người)",
                            Price = 899000m,
                            TagsJson = "[]"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 4, 9, 7, 28, 51, 777, DateTimeKind.Utc).AddTicks(4636),
                            IsAvailable = true,
                            Name = "Lẩu Nấm Chim Câu",
                            Price = 550000m,
                            TagsJson = "[]"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 4, 9, 7, 28, 51, 777, DateTimeKind.Utc).AddTicks(4637),
                            IsAvailable = true,
                            Name = "Chè Dưỡng Nhan",
                            Price = 35000m,
                            TagsJson = "[]"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 4, 9, 7, 28, 51, 777, DateTimeKind.Utc).AddTicks(4638),
                            IsAvailable = true,
                            Name = "Bánh Tiramisu",
                            Price = 55000m,
                            TagsJson = "[\"Must Try\"]"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 4, 9, 7, 28, 51, 777, DateTimeKind.Utc).AddTicks(4639),
                            IsAvailable = true,
                            Name = "Kem Trái Dừa",
                            Price = 45000m,
                            TagsJson = "[]"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 4, 9, 7, 28, 51, 777, DateTimeKind.Utc).AddTicks(4641),
                            IsAvailable = true,
                            Name = "Trái Cây Thập Cẩm",
                            Price = 60000m,
                            TagsJson = "[]"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 4, 9, 7, 28, 51, 777, DateTimeKind.Utc).AddTicks(4646),
                            IsAvailable = true,
                            Name = "Bánh Pudding Xoài",
                            Price = 40000m,
                            TagsJson = "[]"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 4, 9, 7, 28, 51, 777, DateTimeKind.Utc).AddTicks(4648),
                            IsAvailable = true,
                            Name = "Nước Ép Cam",
                            Price = 35000m,
                            TagsJson = "[]"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 4, 9, 7, 28, 51, 777, DateTimeKind.Utc).AddTicks(4649),
                            IsAvailable = true,
                            Name = "Bia Heineken",
                            Price = 25000m,
                            TagsJson = "[]"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 4, 9, 7, 28, 51, 777, DateTimeKind.Utc).AddTicks(4650),
                            IsAvailable = true,
                            Name = "Trà Đào Cam Sả",
                            Price = 45000m,
                            TagsJson = "[]"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 4, 9, 7, 28, 51, 777, DateTimeKind.Utc).AddTicks(4652),
                            IsAvailable = true,
                            Name = "Cà Phê Muối",
                            Price = 35000m,
                            TagsJson = "[]"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 4, 9, 7, 28, 51, 777, DateTimeKind.Utc).AddTicks(4653),
                            IsAvailable = true,
                            Name = "Soda Việt Quất",
                            Price = 40000m,
                            TagsJson = "[]"
                        });
                });

            modelBuilder.Entity("RestaurantMS.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StaffId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TableId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("StaffId");

                    b.HasIndex("TableId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("RestaurantMS.Domain.Entities.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("SpecialNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("RestaurantMS.Domain.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CashierId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("InvoicePdfUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Method")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ServiceFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VatAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("VoucherCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("RestaurantMS.Domain.Entities.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BookingCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GuestCount")
                        .HasColumnType("int");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReservedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TableId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TableId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("RestaurantMS.Domain.Entities.Table", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.ToTable("Tables");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AreaId = 1,
                            Capacity = 4,
                            Name = "Bàn T1.01",
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            AreaId = 1,
                            Capacity = 4,
                            Name = "Bàn T1.02",
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            AreaId = 1,
                            Capacity = 6,
                            Name = "Bàn T1.03",
                            Status = 0
                        },
                        new
                        {
                            Id = 4,
                            AreaId = 1,
                            Capacity = 4,
                            Name = "Bàn T1.04",
                            Status = 0
                        },
                        new
                        {
                            Id = 5,
                            AreaId = 1,
                            Capacity = 4,
                            Name = "Bàn T1.05",
                            Status = 0
                        },
                        new
                        {
                            Id = 6,
                            AreaId = 1,
                            Capacity = 6,
                            Name = "Bàn T1.06",
                            Status = 0
                        },
                        new
                        {
                            Id = 7,
                            AreaId = 1,
                            Capacity = 4,
                            Name = "Bàn T1.07",
                            Status = 0
                        },
                        new
                        {
                            Id = 8,
                            AreaId = 1,
                            Capacity = 4,
                            Name = "Bàn T1.08",
                            Status = 0
                        },
                        new
                        {
                            Id = 9,
                            AreaId = 1,
                            Capacity = 6,
                            Name = "Bàn T1.09",
                            Status = 0
                        },
                        new
                        {
                            Id = 10,
                            AreaId = 1,
                            Capacity = 4,
                            Name = "Bàn T1.10",
                            Status = 0
                        },
                        new
                        {
                            Id = 11,
                            AreaId = 2,
                            Capacity = 8,
                            Name = "Phòng VIP 1",
                            Status = 0
                        },
                        new
                        {
                            Id = 12,
                            AreaId = 2,
                            Capacity = 8,
                            Name = "Phòng VIP 2",
                            Status = 0
                        },
                        new
                        {
                            Id = 13,
                            AreaId = 2,
                            Capacity = 8,
                            Name = "Phòng VIP 3",
                            Status = 0
                        },
                        new
                        {
                            Id = 14,
                            AreaId = 2,
                            Capacity = 8,
                            Name = "Phòng VIP 4",
                            Status = 0
                        },
                        new
                        {
                            Id = 15,
                            AreaId = 2,
                            Capacity = 8,
                            Name = "Phòng VIP 5",
                            Status = 0
                        },
                        new
                        {
                            Id = 16,
                            AreaId = 3,
                            Capacity = 2,
                            Name = "Bàn ST.1",
                            Status = 0
                        },
                        new
                        {
                            Id = 17,
                            AreaId = 3,
                            Capacity = 2,
                            Name = "Bàn ST.2",
                            Status = 0
                        },
                        new
                        {
                            Id = 18,
                            AreaId = 3,
                            Capacity = 2,
                            Name = "Bàn ST.3",
                            Status = 0
                        },
                        new
                        {
                            Id = 19,
                            AreaId = 3,
                            Capacity = 2,
                            Name = "Bàn ST.4",
                            Status = 0
                        },
                        new
                        {
                            Id = 20,
                            AreaId = 3,
                            Capacity = 2,
                            Name = "Bàn ST.5",
                            Status = 0
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("RestaurantMS.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("RestaurantMS.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestaurantMS.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("RestaurantMS.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RestaurantMS.Domain.Entities.MenuItem", b =>
                {
                    b.HasOne("RestaurantMS.Domain.Entities.Category", "Category")
                        .WithMany("MenuItems")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("RestaurantMS.Domain.Entities.Order", b =>
                {
                    b.HasOne("RestaurantMS.Domain.Entities.ApplicationUser", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RestaurantMS.Domain.Entities.Table", "Table")
                        .WithMany("Orders")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Staff");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("RestaurantMS.Domain.Entities.OrderDetail", b =>
                {
                    b.HasOne("RestaurantMS.Domain.Entities.MenuItem", "MenuItem")
                        .WithMany()
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RestaurantMS.Domain.Entities.Order", "Order")
                        .WithMany("Details")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("RestaurantMS.Domain.Entities.Payment", b =>
                {
                    b.HasOne("RestaurantMS.Domain.Entities.Order", "Order")
                        .WithOne("Payment")
                        .HasForeignKey("RestaurantMS.Domain.Entities.Payment", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("RestaurantMS.Domain.Entities.Reservation", b =>
                {
                    b.HasOne("RestaurantMS.Domain.Entities.Table", "Table")
                        .WithMany()
                        .HasForeignKey("TableId");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("RestaurantMS.Domain.Entities.Table", b =>
                {
                    b.HasOne("RestaurantMS.Domain.Entities.Area", "Area")
                        .WithMany("Tables")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("RestaurantMS.Domain.Entities.Area", b =>
                {
                    b.Navigation("Tables");
                });

            modelBuilder.Entity("RestaurantMS.Domain.Entities.Category", b =>
                {
                    b.Navigation("MenuItems");
                });

            modelBuilder.Entity("RestaurantMS.Domain.Entities.Order", b =>
                {
                    b.Navigation("Details");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("RestaurantMS.Domain.Entities.Table", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
